# A list of devices you want to take the screenshots from
devices([
  "iPhone 11",
   "iPad Pro (12.9-inch) (2nd generation)",
   "iPad Pro (12.9-inch) (3rd generation)",
  "iPhone 11 Pro Max",
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone SE (1st generation)"
])
 
# A list of supported languages
languages([
  'es-ES',
  'en-US'
])
 
# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"
 
# Clears previous screenshots
clear_previous_screenshots true
 
# Latest version of iOS
ios_version '13.5'