# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPad Pro (11-inch) (2nd generation)",
   "iPad Pro (12.9-inch) (2nd generation)",
   "iPad Pro (12.9-inch) (3rd generation)",
   "iPhone 11 Pro",
   "iPhone 11 Pro Max"
])
 
# A list of supported languages
languages([
  'fr-FR',
  'es-ES',
  'en-US',
  'en-GB'
])
 
# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"
 
# Clears previous screenshots
clear_previous_screenshots true
 
# Latest version of iOS
ios_version '14.1'