# A list of devices you want to take the screenshots from
devices([
  "iPhone 12 Pro Max",
  "iPhone 8 Plus",
   "iPad Pro (12.9-inch) (2nd generation)",
   "iPad Pro (12.9-inch) (4th generation)",
   "iPhone 12 mini",
   "iPhone 12 Pro",
   "iPad Air (4th generation)",
   "iPhone 8",
   "iPad Pro (11-inch) (2nd generation)"
])
 
# A list of supported languages
languages([
  'fr-FR',
  'es-ES',
  'en-US',
  'en-GB'
])
 
# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"
 
# Clears previous screenshots
clear_previous_screenshots true
 
# Latest version of iOS
ios_version '14.0'